# Generated by Django 3.2.4 on 2021-07-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_usedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
