# Generated by Django 3.2.4 on 2021-07-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.PositiveIntegerField(default=0, max_length=10),
        ),
    ]
